spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USER_DB}
    password: ${PASSWORD_DB}
    url: ${URL_DB}
  jpa:
    defer-datasource-initialization: true
    properties.hibernate.format_sql: true
    generate-ddl: true
    hibernate.ddl.auto: update

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:info}

api:
  source:
    mymangalist:
      url: 'https://api.jikan.moe/v3'

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 5000