spring:
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate.ddl.auto: update
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 4000