spring:
  datasource:
    driver-class-name: ${DRIVER_DB:com.mysql.cj.jdbc.Driver}
    username: ${USER_DB}
    password: ${PASSWORD_DB}
    url: ${URL_DB}
  jpa:
    defer-datasource-initialization: true
    properties.hibernate.format_sql: true
    generate-ddl: true
    hibernate.ddl.auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.hbm2ddl.import_files: sql/populate-database.sql

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:info}

api:
  source:
    mymangalist:
      url: 'https://api.jikan.moe/v3'
    mangabit:
      url: 'https://manga-bit-api.herokuapp.com/api/v1/'

jwt:
  secret: naruto-uzumaki
  expiration: 86400000

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 6000

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
  show-actuator: true