spring:
  jpa:
    defer-datasource-initialization: true
    properties.hibernate.format_sql: true
    generate-ddl: true
    hibernate.ddl.auto: update

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 4000