spring:
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate.ddl.auto: create
    show-sql: false
    properties:
      javax.persistence.query.timeout: 20000
      hibernate:
        generate_statistics: false
        format_sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 4000