spring:
  datasource:
    driver-class-name: ${DRIVER_DB:com.mysql.cj.jdbc.Driver}
    username: ${USER_DB:root}
    password: ${PASSWORD_DB:manga-jj-password}
    url: ${URL_DB:jdbc:mysql://localhost:3306/mangadb?useSSL=false}
    initialization-mode: always
    data: classpath:/sql/populate-database.sql
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: ${DIALECT_DB:org.hibernate.dialect.MySQL5InnoDBDialect}
    properties:
      javax.persistence.query.timeout: 20000
  jackson:
    serialization:
      write_dates_as_timestamps: false

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}

api:
  source:
    mymangalist:
      url: 'https://api.jikan.moe/v4'
    mangabit:
      url: 'https://manga-bit-api.herokuapp.com/api/v1/'
    mangascrapper:
      url: 'http://localhost:3000/'

jwt:
  secret: naruto-uzumaki
  expiration: 86400000

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 6000

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
  show-actuator: true